var sptool={deBug:!0,doc:{},auto:{},isLoaded:!1,helpTilEnd:!1},consoleLog=function(){};sptool.deBug&&(consoleLog=function(a,b,d,c){"string"==typeof b?console.log("%c| "+a+" %c "+b,"color:"+d+";","color:"+c+";"):(console.log("%c| "+a+" %c\n "+b+"\uff1a","color:"+d+";","color:"+c+";"),console.log(b))});var colorLogFun=function(a,b){return function(d,c){consoleLog(d,c,a,b)}};
LOG={INFO:colorLogFun("#00b1ff","#000"),ERRO:colorLogFun("#ff2700","#000"),WARR:colorLogFun("#ff8900","#000"),SUCC:colorLogFun("#47bf12","#000")};sptool.afterLoaded=[];sptool.regAfterLoaded=function(a){sptool.isLoaded?a():sptool.afterLoaded.push(a)};
sptool.setup=function(a){sptool.doc.create=function(a,b){var g=document.createElement(a),f;for(f in b)g.setAttribute(f,b[f]);return g};sptool.doc.appendToHead=function(a){sptool.regAfterLoaded(function(){sptool.doc.head.appendChild(a)})};sptool.doc.importStacker={};var b=function(a,b,g){return function(f,e,h){"undefined"===typeof e&&(e=f);"undefined"===typeof h&&(h=f);b[g]=f;var k=sptool.doc.create(a,b);k.onload=function(){sptool.doc.importStacker[e]=null;LOG.SUCC("\u532f\u5165\u5b8c\u6210",e)};var l=
function(){LOG.INFO("\u6b63\u5728\u532f\u5165",e);sptool.doc.appendToHead(k)};if(null==sptool.doc.importStacker[h])l();else{var m=sptool.doc.importStacker[h].onload;sptool.doc.importStacker[h].onload=function(){m();l()}}sptool.doc.importStacker[e]=k}};sptool.doc["import"]={css:b("link",{rel:"stylesheet"},"href"),js:b("script",{},"src")};document.addEventListener("DOMContentLoaded",function(){sptool.loaded(a)})};sptool.auto.all=function(){sptool.setup([sptool.auto.jquery,sptool.auto.bootstrap])};
sptool.auto.forClass=function(a){sptool.helpTilEnd=!0;sptool.regAfterLoaded(function(){sptool.doc.head.appendChild(sptool.doc.create("meta",{charset:"UTF-8"}))});sptool.auto.all();var b=sptool.doc.create("title");b.textContent="\u4e59\u73ed09\u90b1\u67cf\u7ff0"+a;sptool.doc.appendToHead(b)};sptool.auto.jquery=function(){sptool.doc["import"].js("https://code.jquery.com/jquery-1.12.0.min.js","jquery");sptool.doc["import"].js("https://code.jquery.com/jquery-migrate-1.2.1.min.js","jquery migrate","jquery")};
sptool.auto.bootstrap=function(){sptool.doc.appendToHead(sptool.doc.create("meta",{name:"viewport",content:"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}));sptool.doc["import"].css("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css","bootstrap CSS");sptool.doc["import"].css("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css","bootstrap theme");sptool.doc["import"].js("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js",
"bootstrap","jquery")};
sptool.loaded=function(a){if(sptool.isLoaded)return!0;sptool.doc.html=document.getElementsByTagName("html")[0];sptool.doc.head=document.getElementsByTagName("head")[0];sptool.doc.body=document.getElementsByTagName("body")[0];sptool.doc.body.setAttribute("style","font-family: \u5fae\u8edf\u6b63\u9ed1\u9ad4");if(sptool.helpTilEnd){var b=document.getElementsByClassName("container"),d=document.getElementsByClassName("container-fluid");0>=b.length&&0>=d.length&&(LOG.ERRO("\u672a\u5957\u7528 bootstrap container","\n\u7cfb\u7d71\u5c07\u81ea\u52d5\u5c07\u5167\u6587\u5957\u7528\u7248\u578b"),
sptool.doc.setOnBootstrapMode())}for(var c in a)a[c]();for(c in sptool.afterLoaded)sptool.afterLoaded[c]();sptool.isLoaded=!0;LOG.WARR("\u88fd\u4f5c\u8072\u660e 0304207","\nsuperTool is made by HANS")};
sptool.doc.setOnBootstrapMode=function(){var a=sptool.doc.body.innerHTML;sptool.doc.body.innerHTML="";var b=sptool.doc.create("div",{"class":"container"}),d=sptool.doc.create("div",{"class":"row"}),c=sptool.doc.create("div",{"class":"row"}),g=sptool.doc.create("div",{"class":"col-md-12"}),f=sptool.doc.create("div",{"class":"col-md-12"});d.appendChild(g);c.appendChild(f);b.appendChild(d);b.appendChild(c);d.innerHTML=a;c.innerHTML="<hr><br>\u70ba\u4e86\u62ef\u6551\u8001\u5e2b\u7684\u773c\u775b\uff0c\u4e0d\u9700\u8981\u518d\u770b\u5230\u64e0\u5728\u5de6\u5074\u7684\u7db2\u9801<br>\u6240\u4ee5\u5728\u6211\u5b78\u904ebootstrap\u4ee5\u53cajavascript\u4e4b\u5f8c<br>\u5beb\u4e86\u500b\u5c0f\u7a0b\u5f0f\u5e6b\u6211\u81ea\u52d5\u5957\u7528bootstrap\u7248\u578b<br>by 0304207";
sptool.doc.body.appendChild(b);var a=b.getElementsByTagName("table"),e;for(e in a)a[e]instanceof Node&&a[e].setAttribute("class","table table-hover")};